# Этап сборки
FROM golang:1.23.1-alpine AS builder

WORKDIR /app

# Копируем файлы go.mod и go.sum и загружаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код и компилируем приложение
COPY . . 
RUN GOOS=linux GOARCH=amd64 go build -o /app/main .

# Финальный образ
FROM alpine:latest

# Устанавливаем Nginx
RUN apk add --no-cache nginx

COPY --from=builder /app /usr/local/bin/
COPY --from=builder /app/nginx.conf /etc/nginx/extra-conf.d/nginx.conf

EXPOSE 80
EXPOSE 443

# Запускаем Nginx и приложение
CMD ["sh", "-c", "nginx && /usr/local/bin/main"]
