version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./  
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt/live/easydev:/etc/nginx/certs'  # Монтируем сертификаты
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./
    networks:
      - dev