networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'  # Конфигурация NGINX
      - './index.html:/usr/share/nginx/html/index.html'  # Фронтенд
      - '/home/admin/certs/easydev:/usr/local/bin/certs'  # Монтирование сертификатов
      - './certs:/usr/local/bin/certs'  # Монтирование сертификатов
    depends_on:
      - backend-v1
      - backend-v2
      - frontend
    networks:
      - dev

  backend-v1:
    build:
      context: ../
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev
  backend-v2:
    build:
      context: ./
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  frontend:
    volumes:
      - /home/admin/frontend:/mnt/frontend
    build:
      context: ./frontend
    networks:
      - dev