version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./ # Путь к Dockerfile для бэкенда
    environment:
      - ENV=dev
      - DBSTRING=host=localhost port=5432 user=postgres password=easydev dbname=postgres sslmode=disable
      - HTTP_SERVER_ADDRESS=0.0.0.0:8082
      - HTTP_SERVER_TIMEOUT=4s
      - HTTP_SERVER_IDLE_TIMEOUT=60s
      - HTTP_SERVER_USER=s4bb4t
    networks:
      - dev

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - './index.html:/usr/share/nginx/html/index.html'
    networks:
      - dev
