networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'  # Конфигурация NGINX
      - './index.html:/usr/share/nginx/html/index.html'  # Фронтенд
      - '/home/admin/certs/easydev:/usr/local/bin/certs'  # Монтирование сертификатов
      - './certs/easydev:/usr/local/bin/certs'  # Монтирование сертификатов
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./  
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  frontend:
    image: nginx:alpine
    volumes:
      - './index.html:/usr/share/nginx/html/index.html' 
    networks:
      - dev
