networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./  
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/home/admin/certs/easydev:/etc/nginx/certs'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  frontend:
    image: nginx:alpine
    volumes:
      - './index.html:/usr/share/nginx/html/index.html'  # Подключаем фронтенд
    networks:
      - dev
