networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './index.html:/usr/share/nginx/html/index.html'  # Подключаем фронтенд
      - '/home/admin/certs/easydev:/usr/local/bin/certs'  # Монтируем сертификаты
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./  # Убедитесь, что у вас есть Dockerfile в этом пути
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  frontend:
    image: nginx:alpine
    volumes:
      - './index.html:/usr/share/nginx/html/index.html'  # Подключаем фронтенд
    networks:
      - dev
