version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './certs:/etc/letsencrypt/live/easydev'  # Путь для сертификатов
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./ # Путь к Dockerfile для бэкенда
    networks:
      - dev

  frontend:
    image: nginx:alpine
    volumes:
      - './index.html:/usr/share/nginx/html/index.html'
    networks:
      - dev
