  env: "local" # local, dev, prod
  dbstring: "host=pg3.sweb.ru port=5432 user=mentalrape password=M4UU96RwWYMZUCE_ dbname=mentalrape sslmode=disable"
  http_server: 
    address: "localhost:8082"
    timeout: 4s 
    idle_timeout: 60s