  env: "prod" # local, dev, prod
  dbstring: "host=localhost port=5432 user=postgres password=easydev dbname=postgres sslmode=disable"
  http_server: 
    address: "0.0.0.0:8082"
    timeout: 4s 
    idle_timeout: 60s
    user: "s4bb4t"