definitions:
  github_com_sabbatD_srest-api_internal_lib_api_response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  github_com_sabbatD_srest-api_internal_lib_todoConfig.Meta:
    properties:
      total_amount:
        type: integer
    type: object
  github_com_sabbatD_srest-api_internal_lib_todoConfig.MetaResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_todoConfig.Todo'
        type: array
      info:
        $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_todoConfig.TodoInfo'
      meta:
        $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_todoConfig.Meta'
    type: object
  github_com_sabbatD_srest-api_internal_lib_todoConfig.Todo:
    properties:
      created:
        type: string
      id:
        type: integer
      isdone:
        type: boolean
      title:
        type: string
    type: object
  github_com_sabbatD_srest-api_internal_lib_todoConfig.TodoInfo:
    properties:
      all:
        type: integer
      completed:
        type: integer
      inwork:
        type: integer
    type: object
  github_com_sabbatD_srest-api_internal_lib_userConfig.AuthData:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  github_com_sabbatD_srest-api_internal_lib_userConfig.TableUser:
    properties:
      admin:
        type: boolean
      block:
        type: boolean
      date:
        type: string
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  github_com_sabbatD_srest-api_internal_lib_userConfig.User:
    properties:
      email:
        type: string
      login:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  internal_http-server_handlers_todo.GetAllResponse:
    properties:
      error:
        type: string
      metaresponse:
        $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_todoConfig.MetaResponse'
      status:
        type: string
    type: object
  internal_http-server_handlers_user.AuthResponse:
    properties:
      error:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
  internal_http-server_handlers_user.GetResponse:
    properties:
      error:
        type: string
      status:
        type: string
      user:
        $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_userConfig.TableUser'
    type: object
  internal_http-server_handlers_user.RegisterResponse:
    properties:
      authdata:
        $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_userConfig.AuthData'
      error:
        type: string
      status:
        type: string
    type: object
externalDocs:
  description: Readme.md from github
  url: https://github.com/sabbatD/srest-api
host: 51.250.113.72:8082
info:
  contact:
    email: s4bb4t@yandex.ru
    name: s4bb4t
  description: This is RESTful-API service for EasyDev.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: sAPI
  version: v0.0.2
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: auth user wuth AuthData
      parameters:
      - description: User auth data
        in: body
        name: AuthData
        required: true
        schema:
          $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_userConfig.AuthData'
      produces:
      - application/json
      responses:
        "200":
          description: Token might be empty
          schema:
            $ref: '#/definitions/internal_http-server_handlers_user.AuthResponse'
      summary: Authentication
      tags:
      - user
  /signup:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User whole data
        in: body
        name: UserData
        required: true
        schema:
          $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_userConfig.User'
      produces:
      - application/json
      responses:
        "200":
          description: AuthData might be empty
          schema:
            $ref: '#/definitions/internal_http-server_handlers_user.RegisterResponse'
      summary: Register user
      tags:
      - user
  /todos:
    get:
      consumes:
      - application/json
      description: Get all todos from the storage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http-server_handlers_todo.GetAllResponse'
            type: array
      summary: Get all todos
      tags:
      - todos
  /user/profile:
    get:
      description: returns whole user data
      produces:
      - application/json
      responses:
        "200":
          description: User data might be empty
          schema:
            $ref: '#/definitions/internal_http-server_handlers_user.GetResponse'
      summary: Profile
      tags:
      - user
    post:
      consumes:
      - application/json
      description: updates whole user data
      parameters:
      - description: User data
        in: body
        name: Userdataa
        required: true
        schema:
          $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_userConfig.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sabbatD_srest-api_internal_lib_api_response.Response'
      summary: Update
      tags:
      - user
swagger: "2.0"
